love.window.setMode(1280, 720)
require('core/math')
require('core/timers')
require('core/control')
require('core/world')
require('core/sprites')
require('core/player')
require('core/states')
require('core/enemies')
require('core/weapons')
cam = require('core/cam')
require('core/ui')
